import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_parquet('green_tripdata_2021-01_cleaned.parquet')

sns.set_style("whitegrid")

fig, ax = plt.subplots(1, 2, figsize=(14, 5))
ax[0].hist(df['trip_distance'], bins=50, edgecolor='black')
ax[0].set_xlabel('Trip Distance (miles)')
ax[0].set_ylabel('Frequency')
ax[0].set_title('Trip Distance Distribution')

ax[1].hist(df['fare_amount'], bins=50, edgecolor='black')
ax[1].set_xlabel('Fare Amount ($)')
ax[1].set_ylabel('Frequency')
ax[1].set_title('Fare Amount Distribution')
plt.tight_layout()
plt.savefig('01_distributions.png', dpi=100, bbox_inches='tight')
plt.close()

fig, ax = plt.subplots(1, 2, figsize=(14, 5))
ax[0].scatter(df['trip_distance'], df['fare_amount'], alpha=0.3, s=10)
ax[0].set_xlabel('Trip Distance (miles)')
ax[0].set_ylabel('Fare Amount ($)')
ax[0].set_title('Distance vs Fare (scatter)')

ax[1].hexbin(df['trip_distance'], df['fare_amount'], gridsize=30, cmap='YlOrRd', mincnt=1)
ax[1].set_xlabel('Trip Distance (miles)')
ax[1].set_ylabel('Fare Amount ($)')
ax[1].set_title('Distance vs Fare (hexbin)')
plt.tight_layout()
plt.savefig('02_distance_vs_fare.png', dpi=100, bbox_inches='tight')
plt.close()

fig, ax = plt.subplots()
payment_counts = df['payment_type'].value_counts()
ax.bar(payment_counts.index.astype(int), payment_counts.values)
ax.set_xlabel('Payment Type')
ax.set_ylabel('Count')
ax.set_title('Payment Type Distribution')
ax.set_xticks([1, 2, 3, 4, 5])
plt.tight_layout()
plt.savefig('03_payment_type.png', dpi=100, bbox_inches='tight')
plt.close()

fig, ax = plt.subplots()
ax.hist(df['passenger_count'], bins=range(0, int(df['passenger_count'].max()) + 2), edgecolor='black')
ax.set_xlabel('Passenger Count')
ax.set_ylabel('Frequency')
ax.set_title('Passenger Count Distribution')
plt.tight_layout()
plt.savefig('04_passenger_count.png', dpi=100, bbox_inches='tight')
plt.close()

fig, ax = plt.subplots()
ratecode_counts = df['RatecodeID'].value_counts().sort_index()
ax.bar(ratecode_counts.index.astype(int), ratecode_counts.values)
ax.set_xlabel('RatecodeID')
ax.set_ylabel('Count')
ax.set_title('RatecodeID Distribution')
plt.tight_layout()
plt.savefig('05_ratecode.png', dpi=100, bbox_inches='tight')
plt.close()

fig, ax = plt.subplots()
ax.hist(df['extra'], bins=20, edgecolor='black')
ax.set_xlabel('Extra Surcharge ($)')
ax.set_ylabel('Frequency')
ax.set_title('Extra Surcharge Distribution')
plt.tight_layout()
plt.savefig('06_extra.png', dpi=100, bbox_inches='tight')
plt.close()

fig, ax = plt.subplots(figsize=(10, 6))
corr_matrix = df[['trip_distance', 'fare_amount', 'passenger_count', 'extra', 'tip_amount']].corr()
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', center=0, ax=ax)
ax.set_title('Correlation Matrix')
plt.tight_layout()
plt.savefig('07_correlation.png', dpi=100, bbox_inches='tight')
plt.close()

fig, ax = plt.subplots()
df.boxplot(column='fare_amount', by='payment_type', ax=ax)
ax.set_xlabel('Payment Type')
ax.set_ylabel('Fare Amount ($)')
ax.set_title('Fare Amount by Payment Type')
plt.suptitle('')
plt.tight_layout()
plt.savefig('08_fare_by_payment.png', dpi=100, bbox_inches='tight')
plt.close()
